# Timeout in seconds that Limine will use before automatically booting.
timeout: 3

/CappuccinOS
    protocol: limine
 
    kernel_path: boot():/boot/CappuccinOS.elf
    cmdline: fat_in_mem=false big_fat_phony

    module_path: boot():/boot/initramfs.img
